import StyledComponentsRegistry from "@/lib/StyledComponentsRegistry";
import ProviderLayout from "@/lib/ProviderLayout";
import Navbar from "@/components/Navbar";
import dynamic from "next/dynamic";
import ClientFooter from "@/components/ClientFooter";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning>
        <StyledComponentsRegistry>
          <ProviderLayout>
            <Navbar />
            {children}
            <ClientFooter />
          </ProviderLayout>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
